// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4fvsu_ynFoyXxjVePFpa89gZpt5TuBik',
    appId: '1:398288943361:web:f928d9bdb614bed7734300',
    messagingSenderId: '398288943361',
    projectId: 'rcroom-69442',
    authDomain: 'rcroom-69442.firebaseapp.com',
    storageBucket: 'rcroom-69442.appspot.com',
    measurementId: 'G-KHSH1450HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMPx7pxggyU9MbPlltCCqZFuQ7v_BWiOQ',
    appId: '1:398288943361:android:e08411a23fd12f7f734300',
    messagingSenderId: '398288943361',
    projectId: 'rcroom-69442',
    storageBucket: 'rcroom-69442.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgtqEcc3KdfMs5fTPIVQoNEC2L2FFJtY4',
    appId: '1:398288943361:ios:552c8159f6810f44734300',
    messagingSenderId: '398288943361',
    projectId: 'rcroom-69442',
    storageBucket: 'rcroom-69442.appspot.com',
    iosClientId: '398288943361-1b47ddci1mdhf5mb5hgvve8cru7lmgg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcroom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgtqEcc3KdfMs5fTPIVQoNEC2L2FFJtY4',
    appId: '1:398288943361:ios:552c8159f6810f44734300',
    messagingSenderId: '398288943361',
    projectId: 'rcroom-69442',
    storageBucket: 'rcroom-69442.appspot.com',
    iosClientId: '398288943361-1b47ddci1mdhf5mb5hgvve8cru7lmgg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.rcroom',
  );
}
